### ISSUE TITLE
TTT: Pointshop Playermodels get reset after role selection.

### ISSUE THREAD

**Issue by xEvolution** [adamdburton/pointshop#165]
Hey,

I'm trying to figure out a weird bug which includes pointshop and TTT. Basically, whenever role selection occurs, if a player has a purchased playermodel from pointshop, it will be set to the default TTT model, which is the CSS Terrorist Skins... obviously.

I've done my deep google researchign on the error, removing line 271, 272, 273 in player_ext.lua doesn't work, and I'm not sure where else to turn...

Any advice or solutions are appreciated.

**Comment by Shinsakuto** [comment]
I have the same problem again, even if a lot of people say that it is fixed, and i tried a lot of things in the player_ext.lua and server settings but nothing seems to work.
