### ISSUE TITLE
Is there's a way to change the PS color?

### ISSUE THREAD

**Issue by uRandomAlex** [adamdburton/pointshop#182]
Is there's a way to change the PS color where write "My Community Pointshop"?
Sorry for bad english.

**Comment by adamdburton** [comment]
Change ```color_white``` on https://github.com/adamdburton/pointshop/blob/master/lua/pointshop/vgui/DPointShopMenu.lua#L462 to something like ```Color(255, 0, 0)```

**Comment by uRandomAlex** [comment]
I dont mean this. I think i find it.
"surface.SetDrawColor(40, 40, 40, 255)" on line #455. I test it right now.

**Comment by uRandomAlex** [comment]
Seems to be working.
