### ISSUE TITLE
Random coloured playermodels (usually black)

### ISSUE THREAD

**Issue by iluh** [adamdburton/pointshop#183]
I've just made a local SteamCMD server to play with friends and I added some playermodels to pointshop. They work but they change their colour usually to black / green / blue / dark grey / black flickering, ...

I confirmed this with 'sv_cheats 1' and 'thirdperson' commands. Besides, friends also
![2015-01-09_00001](https://cloud.githubusercontent.com/assets/10457303/5673971/4f775b4e-97a3-11e4-9453-26c561655caa.jpg)
![2015-01-09_00002](https://cloud.githubusercontent.com/assets/10457303/5673972/4f77fe6e-97a3-11e4-942f-b7edc97edbab.jpg)
![2015-01-09_00003](https://cloud.githubusercontent.com/assets/10457303/5673970/4f75d5b2-97a3-11e4-84ca-f242ab34dc90.jpg)

Besides, after preparing round, sometimes the model changes to a default cs terrorist one...
I don't know what else should I do :/

**Comment by Fuzzik** [comment]
When my server was up I had this problem too. Try setting ttt_playercolor_mode to 0 in your server.cfg

**Comment by iluh** [comment]
It works!! Thank you! :))))

**Comment by Fuzzik** [comment]
No problem
