### ISSUE TITLE
Spectator Trails on Join

### ISSUE THREAD

**Issue by Viscerals** [adamdburton/pointshop#188]
Hello, adamburton & HandsomeMatt

I've recently used your addon which, by the way is working wonderfully on my server. The problem I have with it is when a player dies the spectator trails is turned off, but when a player joins the server and they had a trail enabled before, it shows up and is quite annoying for the users. I've tried my best from what knowledge of coding I have to figure out how to fix this but only led to breaking my server. Is it possible you could please help me fix this problem? I'm really sorry to bother you with, what seems a really easy fix. 

Thank you in advance
Regards, Viscerals

**Comment by HandsomeMatt** [comment]
What game mode is this?

**Comment by Viscerals** [comment]
Murder

**Comment by HandsomeMatt** [comment]
Do you have addons like TTT Spec DM installed or anything

**Comment by Viscerals** [comment]
No, I made sure there weren't any addons interfering before I posted here.

**Comment by HandsomeMatt** [comment]
Can you try this out: https://github.com/adamdburton/pointshop/pull/189

**Comment by Viscerals** [comment]
Will test and come back to you on if it works or not, thank you.

**Comment by Viscerals** [comment]
Is it possible to add you on skype? I understand we don't know each other much, but I'd love to add you and talk to you more about learning to code lua for GMOD.

**Comment by HandsomeMatt** [comment]
http://steamcommunity.com/id/handsome-matt/

**Comment by Viscerals** [comment]
Thank you.

**Comment by Viscerals** [comment]
Still doesn't work, sorry.
