### ISSUE TITLE
if PS_Tab

### ISSUE THREAD

**Issue by MrUnknownGamer** [adamdburton/pointshop#202]
I was wondering if we could add something like if PS_Tab('{Name of tab in __category}') then

This will be very helpful when customizing certain tabs

**Comment by HandsomeMatt** [comment]
What the fook are you talking about, elaborate

**Comment by MrUnknownGamer** [comment]
So if I wanted to say make the background for Donate tab green but everything else will stay default white, I would do 
if PS_Tab('Donate') then
    panel:SetColor('1, 1, 1')
end
