### ISSUE TITLE
pointshop broken?

### ISSUE THREAD

**Issue by MrUnknownGamer** [adamdburton/pointshop#204]
Hi,

So every time ULX/ULIB is installed, ps breaks on TTT. I recently switched to linux and copied all ps files, pointshop mysql, etc. Now people spawn is the grey guy and this error spams the server console
[ERROR] addons/pointshop-master/lua/pointshop/sv_player_extension.lua:287: attempt to index field 'PS_Items' (a nil value)
1. PS_HasItem - addons/pointshop-master/lua/pointshop/sv_player_extension.lua:287
2. PS_HasItemEquipped - addons/pointshop-master/lua/pointshop/sv_player_extension.lua:291
3. fn - addons/pointshop-master/lua/pointshop/sh_init.lua:145
4. unknown - addons/ulib/lua/ulib/shared/hook.lua:107

**Comment by HandsomeMatt** [comment]
uninstall ulx & ulib

**Comment by MrUnknownGamer** [comment]
1.) Who in the right mind would do that?
2.) It was only on linux

**Comment by HandsomeMatt** [comment]
ULX isn't really known for it's compatibility with stuff, it loves to mess with the hook system and quite frankly there are some better admin mods around.

I can't see any way possible for PS_Items to be set to nil unless Player:PS_PlayerInitialSpawn() isn't being called, which it should always be - so unless you can provide any other information, I can't provide any more answers. ( There is probably a better error before all the spam, if you can obtain the console log before the spam starts would be great. )

**Comment by MrUnknownGamer** [comment]
Well im not using linux hosting now and im just using NFO VPS to host my servers on windows, plus, windows has lua refresh
