### ISSUE TITLE
P̶r̶e̶c̶a̶c̶h̶e̶ ̶m̶o̶d̶e̶l̶s̶ ̶a̶n̶d̶ ̶m̶a̶t̶e̶r̶i̶a̶l̶s Possible solution to loading models

### ISSUE THREAD

**Issue by mrpotatofactory** [adamdburton/pointshop#205]
Is it possible to precache all assets before generating the shop?
The server I'm running is full of content and it all needs precaching

```lua
if ITEM.Model then
	util.PrecacheModel(ITEM.Model)
end
```
Isn't the best efficient at caching models, as after full loading the models are loaded without any issue or lag

**Comment by mrpotatofactory** [comment]
```
if ITEM.Model then
	util.PrecacheModel(ITEM.Model)
end
```
Isn't the best efficient at caching models, as after full loading the models are loaded without any issue or lag

**Comment by HandsomeMatt** [comment]
What is the bug???

**Comment by HandsomeMatt** [comment]
Models are already precached, do you want them to not be?

**Comment by mrpotatofactory** [comment]
Not essentially a bug but as a requested feature I fell as though we could perhaps render models every few seconds instead of just a pre-cache. This new way would give people a less chance of crashing as they load every model at once.

**Comment by HandsomeMatt** [comment]
Its done at loading screen however, it makes sense?

**Comment by mrpotatofactory** [comment]
Okay I see what your saying.
However, do you have any suggestions to fix the long load with huge amounts of items?

**Comment by HandsomeMatt** [comment]
Uh, you either have them load at the loading screen or they'll load in the middle of the game, which is pretty stupid...

**Comment by mrpotatofactory** [comment]
So would this work?
```lua
function GM:PlayerAuthed( ply, steamid, uid )
ply:SendLua([[
--Loop to load models
]])
end
```

**Comment by HandsomeMatt** [comment]
No. It'll just not work.
