### ISSUE TITLE
non-scrolling material icons

### ISSUE THREAD

**Issue by Mornedil** [adamdburton/pointshop#207]
It took me a while, especially since I am a lua noob, but here's a suggestion (with fix provided) to allow pointshop to have material icons which are not scrolling:

Change line 151 in DPointShopItem.lua to:
```lua
if self:GetParent():GetParent().Hovered and not data.DisableIconScroll then
```

Then users will be able to put **ITEM.DisableIconScroll = true** as an item property to have static icons.

Usefulness:
It can be useful for items that doesn't have a model representation, but still shouldn't have their icon scrolled (like weapon_fists, or powerup items)

Edit:
A shorter (and maybe better) name could be ITEM.NoScroll

**Comment by HandsomeMatt** [comment]
done in #244
