### ISSUE TITLE
How transfer points from Pdata > to mysql

### ISSUE THREAD

**Issue by DutchPatrick** [adamdburton/pointshop#209]
How transfer points from Pdata > to mysql

**Comment by HandsomeMatt** [comment]
Don't actually think there's a way internally, you can probably do it
easily with external tools, take an SQL dump from SQLite and then import to
your MySQL.

**Comment by DutchPatrick** [comment]
I added a knife to my pointshop, but i don't get it.
Only if i buy i get it for 1 round.
And SingleUse is False
How to fix?

**Comment by HandsomeMatt** [comment]
Wonderful. Closed.

**Comment by DutchPatrick** [comment]
Thanks for the answer, its fixed now :l
