### ISSUE TITLE
Big bug! PLEASE LOOK!

### ISSUE THREAD

**Issue by Th3Unkn0wn** [adamdburton/pointshop#211]
When you remove the pointshop from the addons folder, and restart the server, it's still ingame, how is that possible?? I've reinstalled my servers data, lua and others, but it stil appear ingame?!

HOW TO REMOVE THAT SHIT?

**Comment by HandsomeMatt** [comment]
Learn to use your server. Closed

**Comment by Th3Unkn0wn** [comment]
No it's just your shitty addon that is the problem here.

**Comment by HandsomeMatt** [comment]
That's nice dear.

**Comment by Th3Unkn0wn** [comment]
What about helping me?

**Comment by HandsomeMatt** [comment]
Can't help stupid.

**Comment by Th3Unkn0wn** [comment]
Alright stupid
