### ISSUE TITLE
File not being included

### ISSUE THREAD

**Issue by MrUnknownGamer** [adamdburton/pointshop#214]
```lua
Couldn't include file 'vgui\dpointshopitemloadout.lua' (File not found) (@addons/pointshop-master/lua/pointshop/cl_init.lua (line 11))

```

**Comment by HandsomeMatt** [comment]
because that file does not exist, are you using other addons :+1:

**Comment by meepdarknessmeep** [comment]
+1 i have had this problem forever with my custom pointshop 3

**Comment by MrUnknownGamer** [comment]
Pointshop 3?

Anyway, I am only using the ps_subcategories. I don't think that would cause it though. Other than that, no.

**Comment by Kefta** [comment]
It is causing it then because the file doesn't exist. There's nothing beyond that

**Comment by HandsomeMatt** [comment]
But what's trying to include the file.

**Comment by MrUnknownGamer** [comment]
Never mind. I think I fixed it.

**Comment by MrUnknownGamer** [comment]
Ill reopen this because I am trying to add an extra DPointShop file and I added the 
```
include("vgui/DPointShopThingy")
```
Thingy is just a replacement, but either way, it will not include the file. I added it in the regular cl_init file.

**Comment by HandsomeMatt** [comment]
hot damn you're stupid, this isn't a support forum, include needs the file extension, post on Facepunch or something
