### ISSUE TITLE
Model not working after TTT round starts

### ISSUE THREAD

**Issue by MrUnknownGamer** [adamdburton/pointshop#215]
Title says it all, when equipping you'r player model, when theround starts, it will usually disappear but it will still be equiped in pointshop. 

You must unequip it then reequip it.

**Comment by MrUnknownGamer** [comment]
Seems like NFO doesn't keep their TTT updated. After getting the latest update from github, it seems to work fine! Sorry

**Comment by HandsomeMatt** [comment]
don't trust NFO to do anything right, I recommend you move away from them as soon as possible.

**Comment by MrUnknownGamer** [comment]
I only find them good with server performance.

What would you prefer I go to? (A good, fast, reliable server hoster)
