### ISSUE TITLE
TTT Upgrades not working with new skin

### ISSUE THREAD

**Issue by MrUnknownGamer** [adamdburton/pointshop#217]
https://github.com/MrUnknownGamer/TTTUpgrades

I recently got permission to upload it as a community project by @Tommy228 

Sadly, It does not work with the latest pointshop skin and I am only a basic coder, not that god coder. The new update did something iwht the idea of creating a new tab.

**Comment by HandsomeMatt** [comment]
This isn't a discussion/help forum, especially for non default stuff - please stop posting this crap here or I'll ban you from the repo.

**Comment by MrUnknownGamer** [comment]
Sorry, It was somewhat related to pointshop and somehow the new update broke it. Sorry
