### ISSUE TITLE
pointshop model preview bugged [closed]

### ISSUE THREAD

**Issue by Dogeyy** [adamdburton/pointshop#218]
FYI, I can't view my playermodels right, in the preview, they look 10x as bigger then it is when you equip it, I mean the little previews, not the big one when you clicked on a playermodel's preview.

Any fix for this? (I will include screenshots if necessary)

**Comment by HandsomeMatt** [comment]
screenshots will help

**Comment by HandsomeMatt** [comment]
and please make sure you're using the most recent pointshop

**Comment by Dogeyy** [comment]
if you would give me a second and do a fresh install of the pointshop, as my ftp is pretty slow.

**Comment by Dogeyy** [comment]
Nevermind, the updated version fixed it.

**Comment by HandsomeMatt** [comment]
Thought it might.
