### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by MainFighter** [adamdburton/pointshop#220]
I'm trying to get Pointshop working with MySQL and everytime the server starts when MySQL is enabled the following error happened.

[ERROR] addons/pointshop/lua/pointshop/providers/mysql.lua:59: attempt to call m
ethod 'GetFallback' (a nil value)
  1. GetData - addons/pointshop/lua/pointshop/providers/mysql.lua:59
   2. GetPlayerData - addons/pointshop/lua/pointshop/sv_init.lua:274
    3. PS_LoadData - addons/pointshop/lua/pointshop/sv_player_extension.lua:106
     4. unknown - addons/pointshop/lua/pointshop/sv_player_extension.lua:42

And then this error when I try and add points to myself

[ERROR] addons/pointshop/lua/pointshop/providers/mysql.lua:59: attempt to cal
ethod 'GetFallback' (a nil value)
  1. GetData - addons/pointshop/lua/pointshop/providers/mysql.lua:59
   2. GetPlayerData - addons/pointshop/lua/pointshop/sv_init.lua:274
    3. PS_LoadData - addons/pointshop/lua/pointshop/sv_player_extension.lua:1
     4. unknown - addons/pointshop/lua/pointshop/sv_player_extension.lua:42

Its probably something I've done but I don't know what I have done so.

**Comment by HandsomeMatt** [comment]
This happens because the database isn't connected, it's poor error checking on my part sorry, I'll commit a fix soon.

**Comment by HandsomeMatt** [comment]
981c83b36b421567c57b3d3d703b1b258eaa98e2 should fix the error, but your pointshop still isn't connecting to your database, make sure you configure it properly (not configuring your database properly isn't an issue with pointshop)
