### ISSUE TITLE
Adding weapons

### ISSUE THREAD

**Issue by lilbudgotswag** [adamdburton/pointshop#222]
Alright there NEEDS to be an easier way for me to add and edit the weapons in the shop. I really want to be able to put in m9k but all the tutorials and stuff that I see is just way more complicated then it needs to be. I tried going into the files them selves, but all the methods didn't work. 

Would it REALLY be that hard to add a system to add weapons and change the amount of money everything cost? Please add it in.

**Comment by HandsomeMatt** [comment]
You're an idiot if you can't figure it out

**Comment by lilbudgotswag** [comment]
Even so, you should add it in anyway it would save a lot of time for the people who do know how anyway.

**Comment by HandsomeMatt** [comment]
No I shouldn't - it's the simplest it can be

**Comment by lilbudgotswag** [comment]
Ok you may be right. I really do want to be able to add my own custom weapons and I don't know how. 
Could you explain?

**Comment by HandsomeMatt** [comment]
Make a new file in the same folder as the rest, copy the code from an example weapon and change the strings

**Comment by lilbudgotswag** [comment]
But they're lua files

**Comment by HandsomeMatt** [comment]
Yes

**Comment by lilbudgotswag** [comment]
ok i'll try it one second

**Comment by lilbudgotswag** [comment]
OH I AM AN IDIOT
Thanks man I tried this with a remake mod on the workshop and it didn't work. Really sorry for taking up your time.

**Comment by lilbudgotswag** [comment]
oh wait nevermind. Its still not working. 
<img width="330" alt="screen shot 2015-07-13 at 12 55 00 am" src="https://cloud.githubusercontent.com/assets/13305459/8640717/1d263b7c-28fa-11e5-9649-637bde43b952.png">
and yes I changed it back to lua and restarted gmod
