### ISSUE TITLE
pointshop-mysql missing..

### ISSUE THREAD

**Issue by originalwhitestar** [adamdburton/pointshop#223]
The pointshop-mysql repo is missing, where did it go?

**Comment by HandsomeMatt** [comment]
The provider has been merged into this repo.

**Comment by originalwhitestar** [comment]
So mysql works by default?, also, the whole pointshop resets for all players many times.

**Comment by MrUnknownGamer** [comment]
You will need to go into the sh_config and change the data provider to 'MySQL' Then go into the providers/mysql. Lua (If I remember correctly) and change the values to your MySQL host info.
