### ISSUE TITLE
Adding grouped-by-price named groups

### ISSUE THREAD

**Issue by PatPeter** [adamdburton/pointshop#224]
A series of servers that have changed names multiple times (used to regular them as Matrix Gaming and Eagle Edge gaming before that) groups their models by price:

http://imgur.com/EiegU2U

Is this possible in this codebase of the Pointshop, or is this custom code? If it is custom code for their server, can this be implemented into the current Pointshop?

**Comment by adamdburton** [comment]
https://garrysmods.org/download/33/subcategories-for-pointshop

**Comment by PatPeter** [comment]
Thanks Adam!

I had actually tried downloading another Point Shop version from GarrysMod.org but it failed. Hopefully this one will be successful.
