### ISSUE TITLE
Error Pointshop

### ISSUE THREAD

**Issue by igor1560** [adamdburton/pointshop#230]
Please help I installed everything with the default settings and writes me an error when opening the shop (sorry for the translator if that is not correct) there's a picture of the error 

[ERROR] lua/vgui/dpropertysheet.lua:51: attempt to index a nil value
  1. IsActive - lua/vgui/dpropertysheet.lua:51
   2. unknown - addons/pointshop2/lua/ps2/client/cl_dermaskin_flatui.lua:310

![gm_construct0001](https://cloud.githubusercontent.com/assets/13081995/10410940/d8376d18-6f5a-11e5-80e2-977af267f443.jpg)

**Comment by HandsomeMatt** [comment]
This isn't pointshop 2. Create a ticket on ScriptFodder.
