### ISSUE TITLE
Trials still enabled on death

### ISSUE THREAD

**Issue by M21z** [adamdburton/pointshop#234]
I have always had this issue where on the prop team if you die with a trail on the trail does not holster but on the hunter side the trail holsters, I also have this issue on TTT where after you die with a trail it does not holster it.. These issues have always been there and I have made some threads on facepunch with noone actually helping out or solving this issue.

Is there a way to fix this?

Thanks

~M21z

**Comment by M21z** [comment]
bumb?

**Comment by M21z** [comment]
Im pretty sure the bug has to do with the prop team

**Comment by Herover** [comment]
I've had the same problem. Seems to mostly happen first time someone with a trail joins (on Murder) but it doesn't appear to happen consistently.
Haven't seen much of it the last few months tho.
