### ISSUE TITLE
Playermodels (and other stuff) never work. Always a big ERROR !

### ISSUE THREAD

**Issue by Traziiex** [adamdburton/pointshop#242]
Hello !

I tried many times to find out why the playermodels never work. (Also weapons and trails...)
I don't think it's a problem like : People don't have the models.
They have theme because when they load the server, they download it, and the file comes in their download folder (steam/steamapps/common/garrysmod/garrysmod/download/).

So please... Can you help me !

Thanks !

**Comment by HandsomeMatt** [comment]
not a bug with pointshop, just literally resource.AddFile your models.

**Comment by Traziiex** [comment]
I did that !
