### ISSUE TITLE
Playermodels (and other stuff) never work. Always a big ERROR !

### ISSUE THREAD

**Issue by Traziiex** [adamdburton/pointshop#243]
Hello !

I tried many times to find out why the playermodels never work. (Also weapons and trails...)
I don't think it's a problem like : People don't have the models.
They have theme because when they load the server, they download it, and the file comes in their download folder (steam/steamapps/common/garrysmod/garrysmod/download/).
I have added a file in lua/autorun/server where there is resource.AddFile !
So please... Can you help me !

(Sorry for repost, but someone Closed my issue, and it looks like he didn't really read it...)

Thanks !

**Comment by HandsomeMatt** [comment]
I read it, this isn't a help forum. Go here instead https://facepunch.com/forumdisplay.php?f=65
