### ISSUE TITLE
Items not showing in hand.

### ISSUE THREAD

**Issue by ShadeTrust** [adamdburton/pointshop#252]
In the pointshop it says its equipped but no one can see anything this started after restart. Please help.

**Comment by ShadeTrust** [comment]
bump

**Comment by HandsomeMatt** [comment]
not a bug, probably poor item or gamemode coding

**Comment by HandsomeMatt** [comment]
even if it were a pointshop bug you've literally provided no details

**Comment by ShadeTrust** [comment]
So im using https://steamcommunity.com/sharedfiles/filedetails/?id=506283460 and when a player buys one and spawns he does get it but in the inventory tab it says you have it equiped.
