### ISSUE TITLE
ITEM.Skin Currently not working

### ISSUE THREAD

**Issue by SgtVal** [adamdburton/pointshop#253]
I've got skins to these hats and when i set the skin to like ITEM.Skin = 3 in the file it does not change the skin of the model.

**Comment by xDShot** [comment]
Does it mean this issue has beed fixed or it has just been unfairly ignored?

**Comment by adamdburton** [comment]
The issue needed to include basic information such as the model used and the item file.

**Comment by HandsomeMatt** [comment]
More information would be required for it to be an issue. ITEM.Skin has worked since public release years ago - not really unfairly closed :s
