### ISSUE TITLE
Problem with Data provider

### ISSUE THREAD

**Issue by xpuska513** [adamdburton/pointshop#256]
When i set data provider to 'data' i've got this errors.

[ERROR] addons/pointshop/lua/pointshop/sv_init.lua:274: attempt to index field 'DataProvider' (a nil value)
1. GetPlayerData - addons/pointshop/lua/pointshop/sv_init.lua:274
   1. PS_LoadData - addons/pointshop/lua/pointshop/sv_player_extension.lua:106
   2. unknown - addons/pointshop/lua/pointshop/sv_player_extension.lua:42

Timer Failed! [Simple][@addons/pointshop/lua/pointshop/sv_player_extension.lua (line 39)]

[ERROR] addons/pointshop/lua/pointshop/sv_init.lua:274: attempt to index field 'DataProvider' (a nil value)
1. GetPlayerData - addons/pointshop/lua/pointshop/sv_init.lua:274
   1. PS_LoadData - addons/pointshop/lua/pointshop/sv_player_extension.lua:106
   2. unknown - addons/pointshop/lua/pointshop/sv_player_extension.lua:42

Timer Failed! [Simple][@addons/pointshop/lua/pointshop/sv_player_extension.lua (line 39)]

**Comment by xbeastguyx** [comment]
Valid Providers are as follows:
flatfile - Saved in data folder
json - Similar to flatfile
mysql - Saves to a MySQL database using mysqloo (suggested tmysql)
pdata - Saves to the local SQLite database
tmysql - Saves to a MySQL database using tmysql

**Comment by NuclearFission** [comment]
Adding on to what xbeastguyx said, I looked in the code for how flatfile and json is generated and they are literally the exact same down the the letter.
