### ISSUE TITLE
Bugs abuse

### ISSUE THREAD

**Issue by dok441** [adamdburton/pointshop#260]
When setting discounts for certain groups, append the file sh_config so here: if ply:IsUserGroup('superadmin') then return math.Round(item.Price * 0.15) end Poluchaetsya this situation, if the purchase goes off, but when you bought the item that you can sell, then there vystavlyaetsya price higher discount, for example, the price is 1000 for the original. you have a 25% discount you're buying, but sell from the original price 1000, 75% of it. And if the above discount above, we and so you can do endlessly, you can fix it, I would not disable the selling things.

**Comment by xbeastguyx** [comment]
Change the sell price calculation to follow alongside the purchase price.

**Comment by dok441** [comment]
Yeah, I thought about it, I understand, but I would not change the percentage of the sale.

**Comment by xbeastguyx** [comment]
Just write another return for the rank?

**Comment by dok441** [comment]
Do you have to do just the sales price, was the price that the person with the discount, for example from 1 person, no discount price is 100, and the discount on items and they will cost 30, but the sale of 70, it turns baws, I wanted that, the system would automatically configure the sales price from the discount in the store, that this was not. And it turns out, it will be necessary to put the sales price for all is very little.

**Comment by xbeastguyx** [comment]
It's made so you can optionally change things for some ranks, and possibly modify the selling price.  Just multiply the default return by the discount percent.

**Comment by dok441** [comment]
thanks man
