### ISSUE TITLE
tmsql error

### ISSUE THREAD

**Issue by alotlikebirds** [adamdburton/pointshop#265]
[ERROR] addons/ulib/lua/ulib/shared/hook.lua:109: addons/tokenshop/lua/pointshop/providers/tmysql.lua:78: attempt to index local 'row' (a nil value)
1. fn - [C]:-1
   1. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

Seems like something is causing conflict with ULX

**Comment by alotlikebirds** [comment]
Still getting this error [ERROR] addons/ulib/lua/ulib/shared/hook.lua:109: addons/tokenshop/lua/pointshop/providers/tmysql.lua:78: attempt to index local 'row' (a nil value)
  1. fn - [C]:-1
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

**Comment by HandsomeMatt** [comment]
fixed in #263
