### ISSUE TITLE
Equiping trails/weapons bug

### ISSUE THREAD

**Issue by Srlion** [adamdburton/pointshop#267]
**First my gamemode is arizard's deathrun,**
My problem is if i die while having any equipped trail/weapon, i will need to equip them again, and when i try to equip them again, i see "holster" after clicking on the trail/weapon.
So is there anyway to make trails/weapons equipped all the time? without needing to holster/equip them every round.

**Comment by PandaCollision** [comment]
I also have this problem... Im using the same gamemode, so i think the prep time or something brakes it... Im not too sure. I made a job support ticket on ScriptFodder hopefully someone will actually help. The following is the job cut and pasted... I will pay whoever fixes the pointshop problem, or other issues I have!

"I currently have a death-run running Arizard Neue gamemode. I am using _undefined's pointshop and have CSGO knives integrated. I am in need of small tweaks, they include the following;
One - Create a hook that will force equip and or just re-equip all equipped items at the beginning of the round that the players have "equipped" already in the pointshop (the prep time in deathrun). I have been having problems with the current equitation of items as it sometimes equips and other times it works. It either will equip all or nothing... Weird!
Two - Create a command in which players may disable the trails via a command in chat on client side.
Three - I am also using Niandra's Ghostmode and have it setup, but I would like it not hide the player info above head in game as deaths can see the players name as well as disable shadows for this team.

If you are of knowledge and are willing to help please message me, price may change on your knowledge, experience, time, efficiency, and if other projects occur. Price can change if applicable!"

**Comment by HandsomeMatt** [comment]
Game mode is doing something wrong, we already support many different ways to handle this, game mode isn't handling spawning properly or something.
