### ISSUE TITLE
Convert from PData To MySQL (#209 didn't help)

### ISSUE THREAD

**Issue by iViscosity** [adamdburton/pointshop#269]
I know #209 already asked this, but I was wondering how easy it would be to do this. I already dumped the sv.db 'playerpdata' table and filtered out the Pointshop specific things, but now I'm trying to figure out what I need to change as it's in a slightly different format than what MySQL needs (for example: `INSERT INTO "playerpdata" VALUES('3804972992[PS_Items]','{"skull_follower":{"Equipped":false,"Modifiers":[]},"anger":{"Equipped":true,"Modifiers":[]},"jumppackowner":{"Equipped":true,"Modifiers":[]},"greenblood":{"Equipped":true,"Modifiers":[]},"armor":{"Equipped":true,"Modifiers":[]}}');
INSERT INTO "playerpdata" VALUES('3804972992[PS_Points]','999958111');`

(can you tell that's me :D)

Anyways, that's a different format than the 'VALUES( uid, points, items )' from MySQL. What specifically do I need to change? Or am I being stupid and I don't need to change it?

**Comment by HandsomeMatt** [comment]
https://facepunch.com/showthread.php?t=1455401
