### ISSUE TITLE
Pointshop Index error

### ISSUE THREAD

**Issue by stoozey** [adamdburton/pointshop#270]
[currently running deathrun]
When you press F3 to opn the pointshop, it opens, but you cant move your mouse, and if you press F3 again it will open a new one, so they forever overlay, not being able to close them, i also in the top left see my models.
Console Lua Error:

> [ERROR] addons/pointshop-master/lua/pointshop/vgui/dpointshopitem.lua:80: attempt to index field 'Entity' (a nil value)
>  1. SetData - addons/pointshop-master/lua/pointshop/vgui/dpointshopitem.lua:80
  > 2. Init - addons/pointshop-master/lua/pointshop/vgui/dpointshopmenu.lua:253
   > 3. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
  >   4. ToggleMenu - addons/pointshop-master/lua/pointshop/cl_init.lua:27
    >  5. func - addons/pointshop-master/lua/pointshop/cl_init.lua:79
      > 6. unknown - lua/includes/extensions/net.lua:32

>[ERROR] addons/pointshop-master/lua/pointshop/vgui/dpointshopitem.lua:80: attempt to index field >'Entity' (a nil value)
 > 1. SetData - addons/pointshop-master/lua/pointshop/vgui/dpointshopitem.lua:80
 >  2. Init - addons/pointshop-master/lua/pointshop/vgui/dpointshopmenu.lua:253
 >   3. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
  >   4. ToggleMenu - addons/pointshop-master/lua/pointshop/cl_init.lua:27
  >    5. func - addons/pointshop-master/lua/pointshop/cl_init.lua:79
   >    6. unknown - lua/includes/extensions/net.lua:32

>[ERROR] addons/pointshop-master/lua/pointshop/vgui/dpointshopitem.lua:80: attempt to index field >'Entity' (a nil value)
>  1. SetData - addons/pointshop-master/lua/pointshop/vgui/dpointshopitem.lua:80
>   2. Init - addons/pointshop-master/lua/pointshop/vgui/dpointshopmenu.lua:253
>    3. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
>     4. ToggleMenu - addons/pointshop-master/lua/pointshop/cl_init.lua:27
>      5. func - addons/pointshop-master/lua/pointshop/cl_init.lua:79
>       6. unknown - lua/includes/extensions/net.lua:32

**Comment by HandsomeMatt** [comment]
Are you running any custom items?

**Comment by stoozey** [comment]
I'm running playermodels and a vape so far, apart from that its all default

**Comment by stoozey** [comment]
I've got quite a few playermodels, could it be one of them?

**Comment by HandsomeMatt** [comment]
* Are you running the latest version?
* Did these issues begin before or after you added these additional items?
* Can you try running the server without them?
* Does it work on a different gamemode? (Sandbox?)

**Comment by stoozey** [comment]
Running the latest version✔
Still doesn't work on Sanbox ☓
It works when I remove them ✔
(Items were added straight away)

**Comment by HandsomeMatt** [comment]
Yeah your items aren't working properly. You're probably missing models or something.

**Comment by stoozey** [comment]
Okay, thanks. 👍 :)
