### ISSUE TITLE
Point save problem

### ISSUE THREAD

**Issue by Deadalus3010** [adamdburton/pointshop#271]
Hello,

Ps wont save any Points, when they disconnect and reconnect reset to 0.
Map change, reset to 0.
Restart, reset to 0.

I didnt changed anything from the files, only named my Points to "Dollar".

**Comment by HandsomeMatt** [comment]
MySQL or what?

**Comment by Deadalus3010** [comment]
No, I currently have no MySQL Server installed.

**Comment by Deadalus3010** [comment]
Nvm, fixed it.

**Comment by HandsomeMatt** [comment]
care to mention what was wrong and how you managed to fix it so people in the future can avoid the issue you were having?

**Comment by Deadalus3010** [comment]
Sorry, I forgot it.

My Server is really old now (~3 years or so) and the sv.db file was.. I dunno.. overloaded? 
But I saved the file, deleted it and restarted the Server. Now everything works well.
