### ISSUE TITLE
attempt to index local 'model' (a nil value)

### ISSUE THREAD

**Issue by SirChris93** [adamdburton/pointshop#275]
I am getting this error message in console, Idk why.

[ERROR] addons/pointshop-master/lua/pointshop/vgui/dpointshoppreview.lua:82: attempt to index local 'model' (a nil value)
1. DrawOtherModels - addons/pointshop-master/lua/pointshop/vgui/dpointshoppreview.lua:82
2. unknown - addons/pointshop-master/lua/pointshop/vgui/dpointshoppreview.lua:42

**Comment by HandsomeMatt** [comment]
You have an item that doesn't have a valid model.

**Comment by SirChris93** [comment]
But I have everything set appropriatley

**Comment by HandsomeMatt** [comment]
Check again.
