### ISSUE TITLE
Items not re equipping on respawn [Deathrun]

### ISSUE THREAD

**Issue by InZertz** [adamdburton/pointshop#278]
Whenever a player dies and then respawned next round, no items reequip, I am using Arizard Deathrun.
If cause this is important, here is the code to the item.

ITEM.Name = 'Alyx'
ITEM.Price = 1000
ITEM.Model = 'models/player/alyx.mdl'

function ITEM:OnEquip(ply, modifications)
	
	if not ply._OldModel then

		ply._OldModel = ply:GetModel()
	
	end
	
	
	
	timer.Simple(1, function() ply:SetModel(self.Model) end)

end

function ITEM:OnHolster(ply)

	if ply._OldModel then
		
		ply:SetModel(ply._OldModel)
	
	end

end

**Comment by lindinoPT** [comment]
I'm also using Arizard Deathrun and I'm having this same exact issue! It's driving me insane!

**Comment by HandsomeMatt** [comment]
Arizard Deathrun is coded poorly and doesn't respawn players correctly. Not else I can say, not really gonna put some hacky workaround in to compensate for a poorly made gamemode. You can nag Arizard if you want.
