### ISSUE TITLE
Whatever tab is the first shown doesn't show items

### ISSUE THREAD

**Issue by end360** [adamdburton/pointshop#282]
Running latest build of PS. Items in the first tab don't show for some reason. First it was accessories so I just got rid of the tab. Now the hats don't show because it became first.

**Comment by FappyMcFap** [comment]
I had the same issue. Downgrading to Pointshop 1.3.0 fixed the issue for me.

**Comment by end360** [comment]
I just made an empty new category to fix it and made it the first.

**Comment by end360** [comment]
To fix it I disabled the delay on loading items, something about that was causing it but I couldn't find out what.
