### ISSUE TITLE
Pointshop added weapons.

### ISSUE THREAD

**Issue by WolfGFL** [adamdburton/pointshop#283]
When I open pointshop I see all CS:GO knives and it came with a set point price of 20000 but I did not add them. I cant figure out how to get rid of them, I check all folders and there is no sign of these weapons. Thanks for reading my issue.

**Comment by handsomematt** [comment]
By default Pointshop has the HL2 weapons: https://github.com/adamdburton/pointshop/tree/master/lua/pointshop/items/weapons

If you're getting CS:GO knives in there you probably have a steam workshop addon (for CS:GO knives) adding them to Pointshop.
