### ISSUE TITLE
Player models dissapear after round starts

### ISSUE THREAD

**Issue by Phantxm** [adamdburton/pointshop#68]
We're having an issue on our server where the player models will revert back to the default model once the round starts. 
We figured it might have just been an issue with custom models, so we tried one of the default models that came with the add-on, and those revert back at round start as well.

A quick Google search and we noticed some others were having this same issue but no one found a solution.

Also, the colors seem to be off when the player has the model equipped. For example, there is a Skeleton model which is has white bones, but when a player is equipped, they are a dark blue, which seems to be an issue with out other models as well. They appear fine in the PointShop display window and the small image, but the issue arises once its equipped.

Is there any way to solve either of these issues? Any help would be gladly appreciated.

**Comment by Shinsakuto** [comment]
I have the same problem again, even if a lot of people say that it is fixed, and i tried a lot of things in the player_ext.lua and server settings but nothing seems to work.
